# Generated by Django 4.2.2 on 2023-06-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0002_alter_producto_categoria_alter_producto_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
