# Generated by Django 4.2.2 on 2023-06-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0003_producto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
