# Generated by Django 4.2.2 on 2023-06-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0004_producto_img2_producto_img3_producto_img4'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
