# Generated by Django 4.2.2 on 2023-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0005_categoria_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCheckout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=5000)),
            ],
        ),
    ]
