# Generated by Django 4.2.2 on 2023-10-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0007_carritocheckout_checkout_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(max_length=20),
        ),
    ]
