# Generated by Django 4.2.2 on 2023-10-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0010_remove_producto_colores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brosback.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brosback.producto')),
            ],
        ),
    ]
