# Generated by Django 4.2.6 on 2024-01-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0011_productocolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoColorTamaño',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brosback.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brosback.producto')),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brosback.tamaño')),
            ],
        ),
        migrations.RemoveField(
            model_name='productotamaño',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productotamaño',
            name='tamaño',
        ),
        migrations.DeleteModel(
            name='ProductoColor',
        ),
        migrations.DeleteModel(
            name='ProductoTamaño',
        ),
    ]
