# Generated by Django 4.2.6 on 2024-01-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0012_productocolortamaño_remove_productotamaño_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='img4',
        ),
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagenesproductos/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brosback.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brosback.producto')),
            ],
        ),
    ]
