# Generated by Django 4.2.6 on 2024-01-23 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0013_remove_producto_img2_remove_producto_img3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datoscliente', models.JSONField()),
                ('productos', models.JSONField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('cancelada', 'Cancelada'), ('pendiente', 'Pendiente'), ('realizada', 'Realizada')], max_length=20)),
                ('medio', models.CharField(choices=[('transferencia', 'Transferencia'), ('uala', 'Uala')], max_length=25)),
            ],
        ),
    ]
