# Generated by Django 4.2.6 on 2024-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0014_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='preciototal',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
