# Generated by Django 4.2.6 on 2024-01-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0016_alter_orden_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
