# Generated by Django 4.2.6 on 2024-01-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0017_alter_orden_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='idtransferencia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
