# Generated by Django 4.2.6 on 2024-01-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0018_orden_idtransferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('cancelada', 'Cancelada'), ('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('realizada', 'Realizada')], max_length=20),
        ),
    ]
