# Generated by Django 4.2.6 on 2024-02-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0019_alter_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
