# Generated by Django 4.2.6 on 2024-02-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0020_producto_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aviso', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('costo', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
