# Generated by Django 4.2.6 on 2024-02-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0021_aviso_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='costo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
