# Generated by Django 4.2.6 on 2024-02-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0022_alter_envio_costo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='costo',
            new_name='aDomicilio',
        ),
        migrations.AddField(
            model_name='envio',
            name='aSucursal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
