# Generated by Django 4.2.6 on 2024-02-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0023_rename_costo_envio_adomicilio_envio_asucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='idtransferencia',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
