# Generated by Django 4.2.6 on 2024-04-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0025_orden_precioenvio_orden_precioproductos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='medioenvio',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
