# Generated by Django 4.2.6 on 2024-04-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0026_orden_medioenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoTransferencia',
            fields=[
                ('activo', models.BooleanField(primary_key=True, serialize=False)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnvioGratis',
            fields=[
                ('activo', models.BooleanField(primary_key=True, serialize=False)),
                ('compraminima', models.IntegerField()),
            ],
        ),
    ]
