# Generated by Django 4.2.6 on 2024-09-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0027_descuentotransferencia_enviogratis'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhabilitarWeb',
            fields=[
                ('inhabilitar', models.BooleanField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Inhabilitar web',
                'verbose_name_plural': 'Inhabilitar web',
            },
        ),
        migrations.AlterModelOptions(
            name='carritocheckout',
            options={'verbose_name': 'Carrito generado', 'verbose_name_plural': 'Carritos generados'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Configuracion de color', 'verbose_name_plural': 'Configuracion de colores'},
        ),
        migrations.AlterModelOptions(
            name='descuentotransferencia',
            options={'verbose_name': 'Configuración de descuento por transferencia', 'verbose_name_plural': 'Configuración de descuento por transferencia'},
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'verbose_name': 'Configuración de precios de envío', 'verbose_name_plural': 'Configuración de precios de envío'},
        ),
        migrations.AlterModelOptions(
            name='enviogratis',
            options={'verbose_name': 'Configuración de envío gratis', 'verbose_name_plural': 'Configuración de envío gratis'},
        ),
        migrations.AlterModelOptions(
            name='fototalle',
            options={'verbose_name': 'Guia de talle', 'verbose_name_plural': 'Guias de talle'},
        ),
        migrations.AlterModelOptions(
            name='imagenesproducto',
            options={'verbose_name': 'Configuracion de imagenes de productos por color', 'verbose_name_plural': 'Configuracion de imagenes de productos por color'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden de compra', 'verbose_name_plural': 'Ordenes de compra'},
        ),
        migrations.AlterModelOptions(
            name='productocolortamaño',
            options={'verbose_name': 'Configuración de productos por color, tamaño y stock', 'verbose_name_plural': 'Configuraciónes de productos por color, tamaño y stock'},
        ),
        migrations.AlterModelOptions(
            name='tamaño',
            options={'verbose_name': 'Tamaño', 'verbose_name_plural': 'Tamaños'},
        ),
    ]
