# Generated by Django 4.2.6 on 2024-09-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0028_inhabilitarweb_alter_carritocheckout_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabilitarweb',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inhabilitarweb',
            name='inhabilitar',
            field=models.BooleanField(default=False),
        ),
    ]
