# Generated by Django 4.2.6 on 2024-09-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0029_inhabilitarweb_id_alter_inhabilitarweb_inhabilitar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviogratis',
            name='activo',
        ),
        migrations.AddField(
            model_name='enviogratis',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
