# Generated by Django 4.2.6 on 2024-09-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0030_remove_enviogratis_activo_enviogratis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviogratis',
            name='activo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
