# Generated by Django 4.2.6 on 2024-09-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0031_enviogratis_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
                ('descuento', models.IntegerField()),
                ('validohasta', models.DateField()),
            ],
            options={
                'verbose_name': 'Cupón de descuento',
                'verbose_name_plural': 'Cupónes de descuento',
            },
        ),
    ]
