# Generated by Django 4.2.6 on 2024-09-20 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0032_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brosback.cupon'),
            preserve_default=False,
        ),
    ]
