# Generated by Django 4.2.6 on 2024-09-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0033_orden_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brosback.cupon'),
        ),
    ]
