# Generated by Django 4.2.6 on 2024-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosback', '0034_alter_orden_cupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAcceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Codigo de acceso',
                'verbose_name_plural': 'Codigos de acceso',
            },
        ),
    ]
